"""create transactions table

Revision ID: 4f0767bb636e
Revises: 
Create Date: 2026-09-04 11:36:02.725902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0767bb636e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('client_reference', sa.String(length=64), nullable=False),
    sa.Column('provider_reference', sa.String(length=64), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_type', sa.Enum('STK_PUSH', 'C2B', 'B2C', 'B2B', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'TIMEOUT', 'UNKNOWN', name='transactionstatus'), nullable=False),
    sa.Column('account_reference', sa.String(length=12), nullable=False),
    sa.Column('description', sa.String(length=13), nullable=False),
    sa.Column('provider_response_code', sa.String(length=10), nullable=True),
    sa.Column('provider_response_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_request_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_transactions_client_reference'), 'transactions', ['client_reference'], unique=False)
    op.create_index('ix_transactions_created_at', 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_provider_reference'), 'transactions', ['provider_reference'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_provider_reference'), table_name='transactions')
    op.drop_index('ix_transactions_created_at', table_name='transactions')
    op.drop_index(op.f('ix_transactions_client_reference'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
